name: Building new GCC

on: 
  schedule:
    - cron: '35 0 * * *'
  workflow_dispatch:

env:
  GIT_SECRET: ${{ secrets.GIT_SECRET }}
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  GIT_SECRET_MAIN: ${{ secrets.GIT_SECRET_MAIN }}

jobs:
  build:

    strategy:

      fail-fast: false

      matrix:
        config:
          - ver: "12"
            type: "arm64"
            res: "aarch64-zyc-linux-gnu"
            misc: "gcc"

          - ver: "12"
            type: "arm"
            res: "arm-zyc-linux-gnueabi"
            misc: "gcc"

          - ver: "13"
            type: "arm64"
            res: "aarch64-zyc-linux-gnu"
            misc: "gcc"

          - ver: "13"
            type: "arm"
            res: "arm-zyc-linux-gnueabi"
            misc: "gcc"

          - ver: "14"
            type: "arm64"
            res: "aarch64-zyc-linux-gnu"
            misc: "gcc"

          - ver: "14"
            type: "arm"
            res: "arm-zyc-linux-gnueabi"
            misc: "gcc"

          - ver: "info"
            type: ""
            res: ""
            misc: "info"

    name: GCC-${{ matrix.config.ver }}-${{ matrix.config.type }}
    
    runs-on: ubuntu-22.04

    container: 
      image: zycromerz/tcdocker:v2

    steps:
      - name: Checkout
        if: matrix.config.misc == 'gcc'
        uses: actions/checkout@v2

      - name: Compile GCC
        if: matrix.config.misc == 'gcc'
        run: |
          chmod +x do-now.sh
          bash do-now.sh "${{ matrix.config.res }}" "${{ matrix.config.ver }}" "${{ matrix.config.type }}" "nozip"

      - name: Update Info
        if: matrix.config.misc == 'info'
        run: |
          git clone https://${GIT_SECRET_MAIN}@github.com/Clurfe/gcc-builder.git -b gcc/main
          cd gcc-builder
          echo "$(date +"%Y%m%d")" >> last-build.txt
          git config user.name "Clurfe"
          git config user.email "zycromerz@gmail.com"
          git add last-build.txt
          git commit -sm "update last-build.txt to $(date +"%Y%m%d")"
          git show
          git push --all origin -f