name: Building new GCC aarch64-zyc-linux-gnu

on:
  schedule:
    - cron: '35 1 * * SUN'

jobs:
  build:

    runs-on: ubuntu-latest
  
    container: 
      image: zycromerz/kerneldocker:v2

    steps:
    - uses: actions/checkout@v2
    - name: Compile GCC
      env:
        GIT_SECRET: ${{ secrets.GIT_SECRET }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: |
        chmod +x do-now.sh
        bash do-now.sh "aarch64-zyc-linux-gnu" "12" "arm64" "nozip"